name: Test AWS OIDC Connection

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ROLE_TO_ASSUME: arn:aws:iam::866934333672:role/GitHubActionsOIDCRole

jobs:
  test-oidc:
    name: Test OIDC Auth
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity
